### ISSUE TITLE
No issue, just a shout.

### ISSUE THREAD

**Issue by moremeyou** [ryanhalliday/obsidian-reverse-prompter#1]
Hey there,
This plugin slaps. I use this plugin daily. I dropped a shout in a demo for my own plugin. No need to shout back. Just thought I'd give you a heads up :)

https://youtu.be/Q6_bC2aGKQk?si=CRbE7DMZSJCekm4i

**Comment by ryanhalliday** [comment]
Hey David, I'm glad you like the plugin! Always awesome to hear people are using it! 

Thanks for the shout out & very nicely made video :D
