### ISSUE TITLE
Doesn't seem to work or is taking a very long time with no feedback?

### ISSUE THREAD

**Issue by techy2493** [ryanhalliday/obsidian-reverse-prompter#3]
When I try to run this after putting in my open-ai project api key it and press the prompt button after selecting or at the top of my note it adds the AI> section but I let it sit for several minutes and there is no additional output.

When I try to run it a second time I get a pop that says there is already another query running.

My Open AI dashboard does not show any requests and they key remains in a "never used" state.

I am using Open-AI with a free account right now does it need to be a paid/upgraded account to work?

**Comment by ryanhalliday** [comment]
Hey @techy2493 - did you resolve this issue? What was it in the end? I'd like to add an error message to direct other users in the right direction if I can

**Comment by techy2493** [comment]
So I upgraded to a paid account and got it working for a while, but ran into other issues after getting it working well for a few days. I will try testing it all again after updating and will respond if there's anything I can add.

**Comment by ryanhalliday** [comment]
Happy to fix whatever issue it may be if it's with this plugin - let me know what you find!
